[debug] [2018-10-25T12:48:27.720Z] ----------------------------------------------------------------------
[debug] [2018-10-25T12:48:27.724Z] Command:       /usr/bin/node /usr/local/bin/firebase deploy
[debug] [2018-10-25T12:48:27.724Z] CLI Version:   3.19.1
[debug] [2018-10-25T12:48:27.724Z] Platform:      linux
[debug] [2018-10-25T12:48:27.724Z] Node Version:  v8.10.0
[debug] [2018-10-25T12:48:27.725Z] Time:          Thu Oct 25 2018 08:48:27 GMT-0400 (-04)
[debug] [2018-10-25T12:48:27.725Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-10-25T12:48:27.744Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-10-25T12:48:27.745Z] > authorizing via signed-in user
[debug] [2018-10-25T12:48:27.748Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/sapbe-unimet  
  
 Thu Oct 25 2018 08:48:27 GMT-0400 (-04)
[debug] [2018-10-25T12:48:28.691Z] <<< HTTP RESPONSE 200
[debug] [2018-10-25T12:48:28.692Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/sapbe-unimet/tokens  
  
 Thu Oct 25 2018 08:48:28 GMT-0400 (-04)
[debug] [2018-10-25T12:48:29.381Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'sapbe-unimet'...
[info] 
[info] i  deploying hosting
[info] i  hosting: preparing dist/sapbe directory for upload...
[debug] [2018-10-25T12:48:31.843Z] >>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/sapbe-unimet/uploads/-LPfGDDSJU7P5jvYhKFU?fileCount=17&message=  
  
 Thu Oct 25 2018 08:48:31 GMT-0400 (-04)
[debug] [2018-10-25T12:50:45.397Z] <<< HTTP RESPONSE 410
[debug] [2018-10-25T12:50:45.398Z] <<< HTTP RESPONSE BODY undefined
[debug] [2018-10-25T12:50:45.403Z] TypeError: Cannot read property 'error' of undefined
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:10:13)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:47:25)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
[error] 
[error] Error: An unexpected error has occurred.
